# for testing only
version: '3'

services:
  testapp:
    build: .
    environment:
      TZ: America/New_York
    ports:
    - '8080:8080'
    # volumes:
    #   - /home/brajam/data/webhooks:/data/web-hooker/webhooks

