# for testing only
version: '3'

services:
  testapp:
    build: .
    environment:
      TZ: America/New_York
    ports:
    - '8080:8080'
    # volumes:
    #   - /home/brajam/data/webhooks:/data/web-hooker/webhooks

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

